[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://jalworldguitarcompetition.com/"
  to = "https://jalworldguitarcompetition.com/competition"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 